### ISSUE TITLE
change patch name suggestion to start with issue number

### ISSUE THREAD

**Issue by joachim-n** [unicorn-fail/dreditor#14] opened 2013-09-16 15:00 UTC
The new patchname suggestion feature is very nice.

But it has one big flaw IMO: the patch name is "flag.miscellaneous.1658830-3.patch".

Personally, I really dislike patches that start with the module name. EVERYTHING in my module's folder already starts with the module name, so I can't use autocomplete when applying the patch!

Please consider changing this to something that starts with the issue number. (I use the format ISSUE-COMMENT.PROJECT.DESCRIPTION.patch.)

Another benefit of starting with the issue number is that all patches are listed together in a folder :)

**Comment by star-szr** [comment] 2013-09-16 16:47
Agreed.

**Comment by wimleers** [comment] 2013-09-18 21:51
I disagree. When you're working on many patches (as happens during core development), you'd end up with a whole lot of meaningless numbers, so tab completion in the shell would be rather useless.

IMO it should start with the description. I think the project name (core/module/theme) can be left off actually, that's rather useless. As @joachim-n already says: you usually have the patch file in the module you want to apply it to. The only time it's useful is when you reference it in a Drush make file or something like that. But that's the edge case. The common case is development. Let's optimize for that.

**Comment by joachim-n** [comment] 2013-09-18 22:02
When I'm working on lots of issues, I usually open the issue I'm working on right now, so I can get the issue number from the URL. Also, I'm usually on a local git branch, which again starts with the issue number.

I can see though that with core you'd get a LOT of patches in the root folder. Maybe core needs its own filename pattern?

I do tend to delete patch files quite quickly. They're pretty soon obsolete. If you want them back, you can grab them from the issue. And there's git local branches to check the work so far on an issue.

**Comment by markhalliwell** [comment] 2013-09-18 22:30
I actually agree with both @wimleers and @joachim-n. I think Dreditor has gotten to a point where it needs to define "modes", if you will, to separate desired functionality for certain workflows. Core definitely has a unique set of use cases (given how large it is). Modules and themes are less likely to carry over these workflow patterns because it actually makes things more difficult. Modules/themes use the extension name for many [api-]files and using tab completion in the extension's folder is next to impossible since everything starts with the module/theme name.

That all being said, I'm rather used to any and all patches starting with the nid of the issue on d.o. This helps group them together and is a visual indication of what is a patch (I typically read left to right, so skimming for a `.patch` file is not my first choice).

**Comment by helmo** [comment] 2013-10-07 11:29
+1 for keeping the module name in the filename for contrib... So I would be in favor of separate modes for core and contrib.

PS: Lets not (again) duplicate the discussion in http://drupal.org/node/1054616 (or the issue where this feature was created https://drupal.org/node/1294662#comment-7101102)

**Comment by pfrenssen** [comment] 2013-10-10 07:07
It makes total sense to me to start with the issue number. @wimleers you can use the same pattern for core, just include the core component you are working on: `ISSUE-COMMENT-CORECOMPONENT-DESCRIPTION.patch`.  I always use dashes as delimiters though, unlike the example in OP which uses a mix of dashes and periods.

**Comment by webchick** [comment] 2014-02-08 07:47
Mark asked for my 2 cents. As a core maintainer, ISSUE-COMMENT-....patch naming conventions drive me nuts, because then my workflow becomes:

```
wget https://drupal.org/files/issues/1987406-68-twig-node-theme.patch
git apply --index 1<tab>9<tab>8<tab>7<tab>406-68-twig-node-theme.patch
```

I guess I might be an outlier, but I'd say any heavily active maintainer would hit the same.

I don't see why FIRST_FEW_WORDS_OF_TITLE-ISSUE#-COMMENT# would not work for everyone, core and contrib alike. Two different standards creates friction when users move from one place to another, and you're bound to get support requests about it.

I do see the "left to right" problem, but to me that's very easy. Basically everything in your module (say, Flag module) starts with "flag." These will start with [a-z0-9-]+, making them very easy to pick out in a file listing.

**Comment by markhalliwell** [comment] 2014-02-08 07:49
https://www.lullabot.com/blog/article/strategies-patch-management

**Comment by webchick** [comment] 2014-02-08 07:51
I wrote that article back in 2007, but note that it was a patch management strategy for Drupal websites as a whole, and so included the project name front-and-center. As joachim points out, that has the frustrating [tab][tab][tab] problem, and I agree with Wim that in Dreditor's case, this algorithm should be optimized toward patch creators, not site builders.

**Comment by YesCT** [comment] 2014-02-08 08:24
does it make sense to also update d.o doc Advanced patch contributor guide https://drupal.org/node/1054616 which has a patch name recommendation pattern?

**Comment by joachim-n** [comment] 2014-02-08 09:28
My workflow is:

```
wget https://drupal.org/files/issues/1987406-68-twig-node-theme.patch
```

[double-click filename in the wget output]

```
patch -p1 < [PASTE]
```

**Comment by davereid** [comment] 2014-02-08 17:23
As someone who works extensively with patches in core and contrib, starting patches with the issue nid is the only reliable way to go for me. I can easily upload patches to Drupal.org by typing in the nid of the issue I'm updating, and not having to figure out which patch I had just made. For downloading and applying I typically use `curl [patch url] | git apply --index` where I only need to copy/paste the patch once and don't need to retype it.

**Comment by markhalliwell** [comment] 2014-02-08 19:57
I know that in the past we used to enforce (or at least I learned, at the time, from https://drupal.org/patch/submit) that it should be `NID-PROJECT-DESCRIPTION-COMMENT#`, but that seems to have long since been changed. I suspect we all really need to come up with a standard (that we won't change again). The part I'm in agreement with @webchickenator, is that it should be the same for core **and** contrib. No need to confuse people.

**Comment by sun** [comment] 2014-02-08 22:58
FWIW, I agree with @webchickenator — the broken command line autocompletion caused by issue ID prefixes drives me nuts as well:

I'm currently looking at 365 .patch files in my D8 core directory.  If all of them were prefixed with seemingly random numbers, autocompletion would cease to work.

Technically, I should stay out of this discussion here, because I do not use the facility.  Being on Windows, I'm using a one-click script that automatically generates a `git diff --relative HEAD` and pipes that into `[project].patch`.  After invoking it, I just need to rename the file to fill in a few words to reflect the _topic_, and for the sake of ordering my local files in a sane way, I'm adding a comment number suffix, so as to end up with e.g.:

```
drupal8.install-error-handler.18.patch
drupal8.install-error-handler.20.patch
modules/flag/flag.auth-error.4.patch
```

All of these files are immediately deleted as soon as the patch is committed and the issue is closed.

In the very rare case of needing them for whatever reason later on, then drupal.org still has them, so I simply download the latest.

It is my strong belief that issue IDs (and any other computed ID for that matter) exist and are designed for machines only.  Humans should never ever have to interface or deal with IDs.

Therefore, I think that _if_ issue IDs need to be included for any reason, then the only appropriate place would be at the end of the filename.

Personally, however, I'd vastly prefer to cut down this advisory feature/facility to a mere patch filename suggestion that uses _placeholders_ — because humans have the unique benefit of a _brain_:

```
{project}.[topic].patch
```

Only `{project}` would be prefilled with the actual project name.  `[topic]` is whichever 3-4 word summary that makes you happy.

But again, I shouldn't actually comment here, because I'm sure I'm violating whichever patch file naming "standard" that may or may not exist ;)

**Comment by joachim-n** [comment] 2014-02-09 09:44
> It is my strong belief that issue IDs (and any other computed ID for that matter) exist and are designed for machines only. Humans should never ever have to interface or deal with IDs.

I don't know how you're meant to keep track of things if you don't use IDs!

Example: I am about to review an issue for Flag module where a new patch has been uploaded. I use the issue NID as the prefix for my local git branch. Because if I used a descriptive name, I wouldn't be able to remember how I decided to describe the issue last week or last month or whenever I last looked at it.

**Comment by osopolar** [comment] 2014-09-05 22:21
In my opinion the patch name suggestion should follow the [Advanced patch contributor guide](http://www.drupal.org/node/1054616) on d.o. which currently is: **[project_name]-[short-description]-[issue-number]-[comment-number].patch**

This fits very well to my workflow for site developing: I keep all patch-files in one patch-file-directory (nice for documentation purposes, because it is easy to see which modules got modified; this would be less clear represented if the patch name won't start with the module name). The issue and post number are important to check if there are updates in the issue itself (which is important when a modified module needs to be updated). The disadvantage of keeping the patch files in each modules directory is that it will get deleted when a new version is downloaded by drush (as the whole module-directory will get replaced by the new one).

Anyway, if a patch does not follow the above naming convention I rename it before adding it to the websites repository.

**Comment by davereid** [comment] 2014-09-05 22:26
Whereas I implement patches to a site using make files with https://bitbucket.org/davereid/drush-patchfile. All that information is redundant to me in the patch file name since I store them like this:

``` ini
; @see https://drupal.org/comment/5460918#comment-5460918
; @todo Remove when updating to 7.x-2.0-beta2 or higher
projects[nodequeue][patch][] = "https://drupal.org/files/node-mark-deprecated-1402634-1.patch"

; @see https://drupal.org/node/763454#comment-6070450
projects[noderefcreate][patch][] = "https://drupal.org/files/763454-9.patch"
```

**Comment by markhalliwell** [comment] 2016-08-12 22:21
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Closed as completed by markhalliwell** 2016-08-12 22:21 UTC
Labels: enhancement
