### ISSUE TITLE
constantly prompted to remove greasemonkey version and prevented from intalling

### ISSUE THREAD

**Issue by jmelnik** [unicorn-fail/dreditor#111] opened 2014-02-11 13:39 UTC
Tried to update update dreditor via https://dreditor.org/install, and whenever I visit that page I'm constantly prompted to remove the greasemonkey version. I've removed it (via 'manage user scripts') as well as removed greasemonkey completely, refreshed the page, and cleared the cache several times. No matter what I do I cannot get the install page to do the install. 

Is there some place else I can install from? Or a way to manually install?

Thanks.

![fireshot screen capture 083 - install i dreditor - dreditor_org_install](https://f.cloud.github.com/assets/305856/2137198/9ef8a2e0-9321-11e3-882f-bdf237264868.png)

**Comment by star-szr** [comment] 2014-02-11 16:35
@jmelnik, thanks for the report. What version of Firefox and what OS?

**Comment by jmelnik** [comment] 2014-02-18 18:25
Sorry about that... i should have included it in the original post!

firefox: 27.0.1 (latest afaik)
os: windows xp sp3 (i know, i know-- corporate standard, nothing I can do about it, lol).

**Comment by markhalliwell** [comment] 2014-02-18 18:30
@jmelnik, the script that does this check is https://github.com/dreditor/dreditor.org/blob/7.x/sites/all/themes/dreditor_theme/js/script.js#L69-L78

You can see that it would only show up if dreditor is detected somehow. Do you have an old dreditor extension besides the GM script running? I do not know why you would get this message if dreditor wasn't being invoked somehow.

**Comment by jmelnik** [comment] 2014-02-24 20:44
I scoured my firefox and found what appeared to be some left over dreditor options in about:config. I removed them and now I see the install button!!

Now I'm getting "The add-on could not be downloaded because of a
connection failure on dreditor.org." which I would think is a separate issue. however, I've tried tons of times and get the error every single time. Is there any issue with dreditor.org at this time?

**Comment by markhalliwell** [comment] 2014-02-24 20:50
What version of firefox are you running? There are two reasons for that error to appear:
1. The hash of the XPI is wrong (which it's not, or shouldn't be rather). It's currently `sha1:58ca7dc7e3cd4c45744af90686c148932e69a3b8`. You can check this by going to https://dreditor.org/ajax/dreditor/ff-hash
2. You might need to update FF. I ran into this issue because of an API change between versions: https://github.com/dreditor/dreditor.org/commit/902401c48d0324373ff3b997dbbda450cee2b17d. An older FF version only worked with an upper-case `Hash` key, while newer versions only work with a lower-case `hash` key.

**Comment by markhalliwell** [comment] 2014-02-24 20:51
FWIW, I just tested the install button on the latest stable FF (27.0.1) and it installed just fine.

**Comment by sun** [comment] 2014-05-10 03:14
The Dreditor Firefox extension installed just fine for me today.

The browser used to run the GM script previously.  In fact, the dreditor.org front page actually misinterpreted that and told me that Dreditor is installed already...  However, after disabling GreaseMonkey and reloading the page, I was immediately offered the option to install the Firefox extension.

Thus, can't reproduce the issue either.  Closing for now.  Feel free to follow up here in case this issue occurs again.

**Closed as completed by sun** 2014-05-10 03:14 UTC
Labels: bug
