### ISSUE TITLE
Multi-line selection doesn't work from bottom to top

### ISSUE THREAD

**Issue by yched** [unicorn-fail/dreditor#4] opened 2013-08-27 17:41 UTC
When you want to comment on a bunch of lines, drag-n-drop selection has to start from the top to the bottom.

Clicking on the last line and dragging up to the first only selects the last line

(seen on 1.1.7, Chrome / Linux)

**Comment by star-szr** [comment] 2013-08-27 18:14
Thanks @yched! Closed https://drupal.org/node/2062437 as a duplicate of this issue.

**Comment by wimleers** [comment] 2013-09-03 14:00
I noticed this too :)

**Comment by markhalliwell** [comment] 2016-08-12 22:20
Dreditor is being decommissioned due to the lack of availability of current maintainers and the fact that Drupal.org is becoming more feature rich at a much faster rate than Dreditor itself now.

This decision was also partially made due to the amount of work (complete rewrite) it would take to create an "official" Firefox extension (#256).

If you already have the extension installed, it should continue working for a while until, inevitably,  the markup on Drupal.org changes. It will no longer be updated.

We understand that many of you love this extension, as do we. This isn't the end, in fact, it's a much brighter beginning. All the things we love about Dreditor can, and should, be moved into Drupal.org natively.

For more information, please follow: https://www.drupal.org/node/2779729

**Closed as completed by markhalliwell** 2016-08-12 22:20 UTC
Labels: bug

**Comment by subhojit777** [comment] 2016-08-24 18:24
This issue was moved to dreditor/dreditor#55
