### ISSUE TITLE
dreditor template pages on drupal.org

### ISSUE THREAD

**Issue by jhodgdon-drp** [unicorn-fail/dreditor#301] opened 2020-07-04 21:17 UTC
We're in the process of replacing the Getting Involved Guide on drupal.org with a new and hopefully more navigable Contributor Guide.

I've come across a set of pages in the old Getting Involved Guide that have to do with dreditor, and I'm not sure what to do with them. I don't think they belong in the Contributor Guide per se -- the child pages are marked as "internal use for dreditor project":
https://www.drupal.org/node/1120672

I'm about to delete and redirect the page that is currently the parent of that landing page, so I'll be moving it temporarily to the top level in the Getting Involved Guide. Its node ID and URL will remain the same. But eventually, one of the following will need to happen to this section:

a) Migrate it to a new location on drupal.org -- which probably means new content types (we're not really using Book Page any more) and therefore new node IDs (we would put redirects in place)
b) Move the information to an external web site (maybe part of this GitHub repo?)
c) Delete it if it is no longer needed.

I'd be happy to help with (a) or (c), if you can comment on what the right thing to do is. Thanks!

**Comment by BrianGilbert** [comment] 2020-07-09 01:57
This issue is resolved in Dreditor for Firefox 

https://addons.mozilla.org/en-GB/firefox/addon/dreditor-for-firefox/

https://github.com/BrianGilbert/dreditor-for-firefox

**Comment by jhodgdon-drp** [comment] 2020-07-09 02:14
Do you still need the pages on drupal.org then?

**Comment by BrianGilbert** [comment] 2020-07-09 02:16
@jhodgdon-drp I'm using the pages in the Contributor Guides now, so any other older pages can be removed AFAIC

The pages I'm using are:

- /node/3156940
- /node/3156943

**Comment by BrianGilbert** [comment] 2020-07-09 02:24
@markcarver you should be able to just pull in my dreditor.js and rebuild for the chrome extension DWW has already confirmed that my Firefox version works in Chrome

**Comment by markhalliwell** [comment] 2020-07-09 02:29
The extensions are dead. Have been for quite some time (that's the 1.x branch) The current code base is a completely different beast and is primarily just a diff/patch parser and renderer.

In hindsight, it should probably just be a different project (may split that up this weekend).

I'm not going to continue wasting time on the extensions though. Dreditor was only created because the d.o improvement process too years; that is no longer the case. I strongly recommend that we put our efforts into actually improving d.o directly. Drumm is very responsive and small/incremental changes can likely be added very very quickly there.

**Closed as completed** 2020-07-09 02:30 UTC
