### ISSUE TITLE
dreditor won't paste and is going to lose all my work

### ISSUE THREAD

**Issue by joachim-n** [unicorn-fail/dreditor#117] opened 2014-04-10 08:01 UTC
Dreditor is refusing to paste. Nothing happens when I press the button.

I don't see how I can avoid losing my work.

Could it have an 'emergency rescue' function whereby I can at least get all my comments put into the clipboard?

**Comment by joachim-n** [comment] 2014-04-10 08:02
Issue is https://drupal.org/node/1989262

Problem is repeatable.

**Comment by alexpott** [comment] 2014-04-18 09:31
I get this too. Massive +1 to an emergency rescue button

The javascript error is:

Uncaught TypeError: Cannot read property 'compareDocumentPosition' of undefined VM69:2
document.documentElement.compareDocumentPosition.b VM69:2
Drupal.dreditor.patchReview.sort VM69:2
Drupal.dreditor.patchReview.paste VM69:2
(anonymous function) VM69:3
c.event.handle js_xAPl0qIk9eowy_iS9tNkCWXLUVoat94SQT48UBCFkyQ.js:64
h.handle.o

**Comment by markhalliwell** [comment] 2014-04-22 15:18
This should have already been fixed in https://github.com/dreditor/dreditor/commit/4a1afc24e2966db993f11d3280febfdab710db19 `if (a.compareDocumentPosition)`. It seems, however, that `a` doesn't exist in some cases, additional check should probably be done for both `a` and `b`:

```
if (a && b && a.compareDocumentPosition)
```

**Comment by star-szr** [comment] 2014-04-24 01:01
Made a small PR (#118) to attempt to improve this, I agree some kind of emergency rescue button would be very helpful for these cases. Not sure how to implement that or what that would look like though.

**Comment by markhalliwell** [comment] 2014-04-24 01:08
Ok, I merged it.

`'compareDocumentPosition' of undefined` is what worries me. This means that whatever code is invoking the sort function (pasting), isn't actually sending the right elements. This is likely just a blowback from neochief's GH style changes. I haven't really looked too deep into this, but this should effectively silence any fatals and still allow you to paste.

As far as the "emergency save/restore", that's certainly possible... I would suspect we could store all the comments in localStorage for a particular file review and then if it's opened again, you'd just see them. When we're ready to paste, it would take the localStorage and then sort them appropriately.

@sun, thoughts?

**Comment by markhalliwell** [comment] 2014-04-24 01:13
@joachim-n, when you say "repeatable" I will need the exact file, lines, comments made. This error is hanging on something inside of the review table, I'm just not sure what exactly. I rarely comment on anything except the lines added/removed in (usually) a single file, but if you're including multiple files, git info (edit: headers), etc... knowing what elements are triggering it may help narrow this down.

**Comment by joachim-n** [comment] 2014-04-24 07:56
The comment at https://drupal.org/node/1989262#comment-8668447 was my attempt to recapture what I'd written in Dreditor and lost. I've just gone through that and used Dreditor to review the patch again and put comments in at those same lines, and now it works... :/

**Comment by markhalliwell** [comment] 2014-04-24 17:11
:-/ indeed. This bug feels impossible to track down, seemingly entirely random. It doesn't work and then it does, hopefully this recent commit will help squash some more fatals from popping up. I still want to keep this open though, cause I think using localStorage for each comment per file URL will help some of this. This would also let you open/review other files without losing existing comments (ie: in case one needs to close the current review before pasting for some reason).

**Comment by markhalliwell** [comment] 2014-05-10 17:13
I cannot reproduce this either:
http://monosnap.com/file/DGaoX0dEwCxpAos9gxk0yBS7BdPFPk
Google Chrome 34.0.1847.131 (OSX) Dreditor 1.2.5

**Comment by markhalliwell** [comment] 2014-05-22 23:52
Hopefully this _should_ be fixed in 1.2.6. I've opened #151 as a follow-up.

**Closed as completed by markhalliwell** 2014-05-22 23:52 UTC
Labels: bug
