### ISSUE TITLE
hitbox is strange on "create commit message"

### ISSUE THREAD

**Issue by djdevin** [unicorn-fail/dreditor#1] opened 2013-08-26 13:27 UTC
Chrome 28

The "Create commit message" button can only be clicked when the mouse is in the lower 1/4th of the button.

"make sticky" does not behave this way.

**Comment by davereid** [comment] 2013-08-26 13:35
I can confirm this behavior as well with Chrome 29 on Linux.

**Comment by markhalliwell** [comment] 2013-08-26 14:26
Determined this is because of the absolutely positioned tags.

**Comment by markhalliwell** [comment] 2013-11-01 01:03
I believe this is now fixed due to the D7 version of d.o putting the issue information on the edit page only.

**Closed as completed by markhalliwell** 2013-11-01 01:03 UTC
Labels: bug
